# Generated by Django 4.2 on 2023-04-06 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='sobrevivente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=65)),
                ('sexo', models.CharField(max_length=20)),
                ('últimoLocal', models.CharField(max_length=30)),
                ('inventario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rede_zumbi.items')),
            ],
        ),
    ]
