# Generated by Django 4.2 on 2023-04-06 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rede_zumbi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelDeInfecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infectado', models.BooleanField(default=False)),
                ('nome', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rede_zumbi.sobrevivente')),
            ],
        ),
    ]
