# Generated by Django 4.2 on 2023-04-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede_zumbi', '0003_alter_niveldeinfecao_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='sobrevivente',
            name='idade',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sobrevivente',
            name='pontosDeInfectacao',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
