# Generated by Django 4.2 on 2023-04-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede_zumbi', '0004_sobrevivente_idade_sobrevivente_pontosdeinfectacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='niveldeinfecao',
            name='pontosDeInfectacao',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
