# Generated by Django 4.2 on 2023-04-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rede_zumbi", "0006_alter_sobrevivente_nome"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="niveldeinfecao",
            name="infectado",
        ),
        migrations.AddField(
            model_name="sobrevivente",
            name="infectado",
            field=models.BooleanField(default=False),
        ),
    ]
