# Generated by Django 4.2 on 2023-04-11 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rede_zumbi", "0009_alter_comerciozumbimodel_negociador_1_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="items",
            new_name="ItemsModel",
        ),
        migrations.AlterField(
            model_name="comerciozumbimodel",
            name="negociador_1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="negoiciado_um",
                to="rede_zumbi.sobrevivente",
            ),
        ),
        migrations.AlterField(
            model_name="comerciozumbimodel",
            name="negociador_2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="negociador_dois",
                to="rede_zumbi.sobrevivente",
            ),
        ),
    ]
