# Generated by Django 4.2 on 2023-04-12 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rede_zumbi", "0010_rename_items_itemsmodel_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventario",
            name="sobrrevivente",
        ),
        migrations.AddField(
            model_name="inventario",
            name="nome_sobrevivente",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nome_sobrevivente",
                to="rede_zumbi.sobrevivente",
            ),
            preserve_default=False,
        ),
    ]
