# Generated by Django 4.2 on 2023-04-12 04:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rede_zumbi", "0011_remove_inventario_sobrrevivente_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sobrevivente",
            name="pontosDeInfectacao",
            field=models.IntegerField(null=True),
        ),
    ]
