# Generated by Django 4.2 on 2023-04-15 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rede_zumbi", "0013_remove_inventario_item_inventario_item1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventario",
            name="item1",
        ),
        migrations.RemoveField(
            model_name="inventario",
            name="item2",
        ),
        migrations.RemoveField(
            model_name="inventario",
            name="item3",
        ),
        migrations.RemoveField(
            model_name="inventario",
            name="item4",
        ),
        migrations.AddField(
            model_name="inventario",
            name="item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rede_zumbi.itemsmodel",
            ),
        ),
    ]
