# Generated by Django 4.2 on 2023-04-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rede_zumbi", "0015_inventariomodel_delete_inventario"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventariomodel",
            name="quantidade",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
