# Generated by Django 4.2 on 2023-04-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rede_zumbi", "0016_inventariomodel_quantidade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventariomodel",
            name="quantidade",
            field=models.IntegerField(null=True),
        ),
    ]
