# Generated by Django 4.2 on 2023-04-22 22:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rede_zumbi", "0018_rename_item1_ngc1_comerciozumbimodel_itens_ngc1_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sobrevivente",
            old_name="últimoLocal",
            new_name="ultimoLocal",
        ),
        migrations.AlterField(
            model_name="inventariomodel",
            name="quantidade",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
